Repository woowa-techcamp-2020/hkb-7, pull requests merged in 2020-08, with the labels that each got.

#27 feat: observer pattern을 적용한 프론트엔드 구조 설계
  client/src/App.js
  client/src/api/index.js
  client/src/components/ActivityTable/index.js
  client/src/components/Filter/index.js
  client/src/components/Form/index.js
  client/src/components/Header/index.js
  client/src/components/MonthNavigator/index.js
  client/src/components/SectionNavigator/index.js
  client/src/models/observable.js
  client/src/models/store.js
  client/src/utils/bindEvent.js
  client/src/utils/helper.js
  client/src/views/pages/MainPage/index.js
  client/src/views/sections/ActivitySection/index.js
  server/app.js
  server/controllers/activity.js
  server/models/activity.js
  server/models/model.js
  server/package-lock.json
  server/package.json
  server/routes/activity.js
  server/routes/category.js
  server/routes/index.js
  server/routes/payment-method.js
  server/routes/profile.js
  server/routes/user.js
Labels: api, frontend

#29 Feature/28/new design
  client/package-lock.json
  client/package.json
  client/public/svg/activities.svg
  client/public/svg/calendar.svg
  client/public/svg/cards.svg
  client/public/svg/settings.svg
  client/public/svg/stats.svg
  client/public/svg/target.svg
  client/src/components/ActivityTable/index.js
  client/src/components/ActivityTable/styles.scss
  client/src/components/Filter/index.js
  client/src/components/Filter/styles.scss
  client/src/components/Form/index.js
  client/src/components/Form/styles.scss
  client/src/components/Header/index.js
  client/src/components/Header/styles.scss
  client/src/components/MonthNavigator/index.js
  client/src/components/MonthNavigator/styles.scss
  client/src/components/SectionNavigator/index.js
  client/src/components/SectionNavigator/styles.scss
  client/src/styles/common.scss
  client/src/utils/html.js
  client/src/views/pages/MainPage/index.js
  client/src/views/pages/MainPage/styles.scss
  client/src/views/sections/ActivitySection/index.js
  client/src/views/sections/FormSection/index.js
  client/src/views/sections/FormSection/styles.scss
Labels: frontend

#30 feat: SPA Routing 기능 구현
  client/src/App.js
  client/src/Router.js
  client/src/api/index.js
  client/src/components/MonthNavigator/index.js
  client/src/components/SectionNavigator/index.js
  client/src/models/store.js
  client/src/views/pages/LoginPage/index.js
  client/src/views/pages/MainPage/index.js
  client/src/views/sections/ActivitySection/index.js
  client/src/views/sections/CalendarSection/index.js
  client/src/views/sections/StatisticSection/index.js
  client/webpack.dev.js
  server/app.js
  server/controllers/activity.js
  server/models/activity.js
  server/routes/activity.js
  server/routes/index.js
Labels: frontend

#40 feat: 컴포넌트 구조 재정립
  client/src/components/ActivityTable/index.js
  client/src/components/ActivityTable/styles.scss
  client/src/components/DailyActivityCard/index.js
  client/src/components/DailyActivityCard/styles.scss
  client/src/components/Filter/index.js
  client/src/components/Form/index.js
  client/src/components/Form/styles.scss
  client/src/components/Header/index.js
  client/src/components/MonthBar/index.js
  client/src/components/MonthBar/styles.scss
  client/src/components/MonthNavigator/index.js
  client/src/components/SectionContainer/index.js
  client/src/components/SectionContainer/styles.scss
  client/src/components/SectionNavigator/index.js
  client/src/components/Sections/ActivitySection/index.js
  client/src/components/Sections/ActivitySection/styles.scss
  client/src/components/Sections/CalendarSection/index.js
  client/src/components/Sections/CalendarSection/styles.scss
  client/src/components/Sections/StatisticSection/index.js
  client/src/components/Sections/StatisticSection/styles.scss
  client/src/styles/common.scss
  client/src/views/pages/MainPage/index.js
  client/src/views/pages/MainPage/styles.scss
  client/src/views/sections/FormSection/index.js
Labels: frontend, refactor

#45 feat: 캘린더 페이지 구현
  client/src/components/CalendarTable/index.js
  client/src/components/CalendarTable/styles.scss
  client/src/components/Filter/index.js
  client/src/components/Form/index.js
  client/src/components/Form/styles.scss
  client/src/components/MonthNavigator/styles.scss
  client/src/components/SectionNavigator/styles.scss
  client/src/components/Sections/CalendarSection/index.js
  client/src/styles/common.scss
  client/src/utils/helper.js
Labels: frontend

#43 feat: ActivitySection 내부를 Table, Card, Item 단위로 컴포넌트화
  client/src/api/index.js
  client/src/components/ActivityItem/index.js
  client/src/components/ActivityItem/styles.scss
  client/src/components/ActivityTable/index.js
  client/src/components/DailyActivityCard/index.js
  client/src/components/Filter/index.js
  client/src/models/store.js
  client/src/utils/helper.js
  server/controllers/activity.js
  server/controllers/payment-method.js
  server/routes/payment-method.js
Labels: enhancement, frontend

#44 docs: 목업 이미지 경로 수정
  README.md
  docs/images/compressed-mockup.png
  docs/images/mockup.png
Labels: documentation

#50 feat: addActivity 기능 구현
  client/src/api/index.js
  client/src/components/DailyActivityCard/index.js
  client/src/components/Filter/index.js
  client/src/components/Filter/styles.scss
  client/src/components/Form/index.js
  client/src/models/store.js
  client/src/styles/common.scss
  client/src/utils/constant.js
  client/src/utils/helper.js
  client/src/utils/template.js
  client/webpack.prod.js
  server/app.js
  server/controllers/category.js
  server/models/activity.js
  server/routes/category.js
Labels: api, frontend

#52 docs: 배포 링크, 디자인 리소스 링크 추가
  README.md
Labels: production

#51 hotfix: 모듈을 가져오지 못하는 문제 해결
  client/src/components/SectionContainer/index.js
Labels: production

#54 feat: 자동 배포 구현
  build.sh
  client/src/api/index.js
  client/webpack.dev.js
  client/webpack.prod.js
  server/package.json
Labels: production

#57 feat: Filter 기능 & Activity 업데이트, 삭제 구현
  client/src/Router.js
  client/src/api/index.js
  client/src/components/ActivityItem/index.js
  client/src/components/ActivityItem/styles.scss
  client/src/components/ActivityTable/index.js
  client/src/components/CalendarTable/index.js
  client/src/components/DailyActivityCard/index.js
  client/src/components/Filter/index.js
  client/src/components/Form/index.js
  client/src/components/MonthBar/index.js
  client/src/components/MonthNavigator/index.js
  client/src/models/store.js
  client/src/utils/helper.js
  client/src/utils/template.js
  server/controllers/activity.js
  server/models/activity.js
  server/models/category.js
  server/models/payment-method.js
  server/models/profile.js
  server/models/user.js
  server/routes/activity.js
Labels: api, frontend

#67 hotfix: ejs module 설치
  server/package-lock.json
  server/package.json
Labels: bug, production

#70 feat: cancel edit button
  client/src/components/DailyActivityCard/styles.scss
  client/src/components/Form/index.js
  client/src/components/Form/styles.scss
  client/src/models/store.js
Labels: enhancement, frontend

#71 fix: userId를 token으로 수정
  client/src/models/store.js
Labels: bug

#72 v1.0.3 배포
  client/src/components/DailyActivityCard/styles.scss
  client/src/components/Form/index.js
  client/src/components/Form/styles.scss
  client/src/models/store.js
Labels: production
