Repository woowa-techcamp-2020/hkb-7, pull requests merged in 2020-07, with the labels that each got.

#1 docs: issue template 및 pull request template 추가
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#3 docs: 이슈 템플릿에 작업의 크기 항목 추가
  .github/ISSUE_TEMPLATE.md
Labels: documentation

#10 Backend Server Generate + DB 연결 코드 추가
  server/.gitignore
  server/app.js
  server/bin/www
  server/models/index.js
  server/package-lock.json
  server/package.json
  server/routes/index.js
  server/routes/users.js
Labels: backend, database

#11 feat: 웹팩과 바벨을 사용한 프론트엔드 기본 개발 환경 구성
  .gitignore
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/public/images/webpack.png
  client/public/index.html
  client/src/app.js
  client/src/components/Content/Content.js
  client/src/components/Content/index.js
  client/src/components/Content/index.scss
  client/src/components/Page.js
  client/src/components/Title/Title.js
  client/src/components/Title/index.js
  client/src/components/Title/index.scss
  client/src/style.scss
  client/src/utils/math.js
  client/webpack.dev.js
  client/webpack.prod.js
Labels: frontend

#12 docs: README.md에 ERD 이미지 추가
  README.md
  docs/images/database-erd.png
Labels: database, documentation

#17 docs: 데이터베이스 변경사항 ERD 이미지에 반영
  docs/images/database-erd.png
Labels: backend, database, documentation

#16 feat: 데이터베이스 MVC 구조 적용 및 기본 CRUD 기능 구현
  server/app.js
  server/bin/www.js
  server/controllers/activity.js
  server/controllers/category.js
  server/controllers/payment-method.js
  server/controllers/profile.js
  server/controllers/user.js
  server/models/activity.js
  server/models/category.js
  server/models/index.js
  server/models/model.js
  server/models/payment-method.js
  server/models/profile.js
  server/models/query.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/activity.js
  server/routes/category.js
  server/routes/index.js
  server/routes/payment-method.js
  server/routes/profile.js
  server/routes/user.js
  server/routes/users.js
  shared/utils/helper.js
Labels: backend, database

#22 feat: 컴포넌트 구조 설정 및 기본 HTML 템플릿 작성
  client/public/index.html
  client/src/App.js
  client/src/app.js
  client/src/components/ActivityTable/index.js
  client/src/components/ActivityTable/styles.scss
  client/src/components/Content/Content.js
  client/src/components/Content/index.js
  client/src/components/Content/index.scss
  client/src/components/Filter/index.js
  client/src/components/Filter/styles.scss
  client/src/components/Form/index.js
  client/src/components/Form/styles.scss
  client/src/components/Header/index.js
  client/src/components/Header/styles.scss
  client/src/components/MonthNavigator/index.js
  client/src/components/MonthNavigator/styles.scss
  client/src/components/Page.js
  client/src/components/SectionNavigator/index.js
  client/src/components/SectionNavigator/styles.scss
  client/src/components/Title/Title.js
  client/src/components/Title/index.js
  client/src/components/Title/index.scss
  client/src/main.js
  client/src/style.scss
  client/src/styles/common.scss
  client/src/styles/reset.scss
  client/src/utils/element.js
  client/src/utils/math.js
  client/src/views/pages/LoginPage/index.js
  client/src/views/pages/LoginPage/styles.scss
  client/src/views/pages/MainPage/index.js
  client/src/views/pages/MainPage/styles.scss
  client/src/views/sections/ActivitySection/index.js
  client/src/views/sections/ActivitySection/styles.scss
  client/src/views/sections/CalendarSection/index.js
  client/src/views/sections/CalendarSection/styles.scss
  client/src/views/sections/StatisticSection/index.js
  client/src/views/sections/StatisticSection/styles.scss
  client/webpack.dev.js
  client/webpack.prod.js
  server/app.js
Labels: frontend

#21 Passport-local 인증 구현
  server/app.js
  server/controllers/user.js
  server/models/model.js
  server/package-lock.json
  server/package.json
  server/routes/activity.js
  server/routes/category.js
  server/routes/index.js
  server/routes/payment-method.js
  server/routes/profile.js
  server/routes/user.js
  server/utils/auth.js
Labels: api, backend

#26 feat: 프론트엔드 컴포넌트 구조 개선
  client/src/App.js
  client/src/components/ActivityTable/index.js
  client/src/components/Filter/index.js
  client/src/components/Form/index.js
  client/src/components/Header/index.js
  client/src/components/MonthNavigator/index.js
  client/src/components/SectionNavigator/index.js
  client/src/main.js
  client/src/views/pages/MainPage/index.js
  client/src/views/sections/ActivitySection/index.js
Labels: enhancement, frontend
